name: client deploy

on:
  workflow_run:
    workflows: ["Vite ubild"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      run: |
        ssh root@31.128.40.203
        Temikadza_2002
        ls
