name: client deploy

on:
  workflow_run:
    workflows: ["Vite ubild"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/client/steam-info-checker-client
          git pull
          git status
          npm install
          npm run build
          pm2 restart server
