name: client deploy

on:
  workflow_run:
    workflows: ["Vite ubild"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      run: sshpass -p Temikadza_2002 ssh -tt root@31.128.40.203
