name: client deploy

on:
  workflow_run:
    workflows: ["Vite ubild"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Test
      uses: webfactory/ssh-agent@v0.3.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}
    - name: Deploy using ssh
      run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd client/ && ls && exit"
